---
title: "MGMT Project Analysis 10-10-18"
output: html_notebook
---
```{r}
#dependencies
library(ggplot2)
library(reshape2)

#data import
dirPath <- '~/Dropbox/Postdoc/MGMT Project/BSAS Results/BSAS Analysis R Project'
data <- read.csv(file.path(dirPath, "MGMT_Infinium_BSAS.csv"))
```

```{r}
#scatterplot of all data 
ggplot(data, aes(x=MGMT_BSAS, y=MGMT_Infinium, color=HM_status)) + 
  geom_point() + 
  geom_text(aes(label=Patient), nudge_x=0.025) +
  labs(x= "Percent CpG Methylation (BSAS)", y = "Probability of Methylation (Infinium Array)")
```
```{r}
cor.test(data$MGMT_BSAS, data$MGMT_Infinium, method = "spearman", conf.level = 0.95)
```
```{r}
cor.test(data$MGMT_BSAS, data$MGMT_Infinium, method = "pearson", conf.level = 0.95)
```

```{r}
#aggregate data
agdata_Infinium <- aggregate(data$MGMT_Infinium, by=list(Patient=data$Patient, Tumor=data$Tumor, HM_status=data$HM_status), mean)
agdata_BSAS <-aggregate(data$MGMT_BSAS, by=list(Patient=data$Patient, Tumor=data$Tumor, HM_status=data$HM_status), mean)
agdata <- merge(agdata_Infinium, agdata_BSAS, by = c("Patient", "Tumor", "HM_status"))
colnames(agdata)[which(names(agdata) == "x.x")] <- "MGMT_Infinium"
colnames(agdata)[which(names(agdata) == "x.y")] <- "MGMT_BSAS"

#define subsets
agdata_primary <- agdata[which(agdata$Tumor == 'Primary'),]
agdata_recurrence <- agdata[which(agdata$Tumor == 'Recurrence'),]
agdata_HM <- agdata[which(agdata$HM_status == 'HM'),]
agdata_nonHM <- agdata[which(agdata$HM_status == 'nonHM'),]
```

```{r}

#scatterplot of aggregate data
ggplot(agdata, aes(x=MGMT_BSAS, y=MGMT_Infinium, color=HM_status)) + 
  geom_point() + 
  geom_text(aes(label=Patient), nudge_x=0.025) +
  labs(x= "Percent CpG Methylation (BSAS)", y = "Probability of Methylation (Infinium Array)")
```
```{r}
cor.test(agdata$MGMT_BSAS, agdata$MGMT_Infinium, method = "spearman", conf.level = 0.95)
```
```{r}
cor.test(agdata$MGMT_BSAS, agdata$MGMT_Infinium, method = "spearman", conf.level = 0.95)
```

```{r}
#boxplot - Infinium Array data for all patients
ggplot(data, aes(x=factor(Patient), y=MGMT_Infinium)) +
  geom_boxplot(aes(colour=Tumor)) +
  facet_grid(. ~ HM_status, scales = "free", space = "free", labeller = labeller(HM_status = c(HM = "Hypermutated", nonHM = "Non-Hypermutated"))) +
  theme(strip.text.x = element_text(size=12), strip.text.y = element_text(size=12)) +
  geom_hline(yintercept = 0.358, col = "red", linetype="dotted") +
  labs(x= "Patient", y= "Probability of Methylation", title = "MGMT Methylation Infinium Array Data By Hypermutation Status") +
  theme(plot.title = element_text(hjust = 0.5, face="bold"))
```
```{r}
#boxplot - BSAS data for all patients
ggplot(data, aes(x=factor(Patient), y=MGMT_BSAS)) +
  geom_boxplot(aes(colour=Tumor)) +
  facet_grid(. ~ HM_status, scales = "free", space = "free", labeller = labeller(HM_status = c(HM = "Hypermutated", nonHM = "Non-Hypermutated"))) +
  theme(strip.text.x = element_text(size=12), strip.text.y = element_text(size=12)) +
  labs(x= "Patient", y= "Percentage CpG Methylation", title = "MGMT Methylation BSAS Data By Hypermutation Status") +
  theme(plot.title = element_text(hjust = 0.5, face="bold"))
```
```{r}
#boxplot - Infinium Array data for each tumor type
ggplot(agdata, aes(x=Tumor, y=MGMT_Infinium)) +
  geom_boxplot(aes(colour=Tumor)) +
  facet_grid(. ~ HM_status, labeller = labeller(HM_status = c(HM = "Hypermutated", nonHM = "Non-Hypermutated"))) +
  theme(strip.text.x = element_text(size=12), strip.text.y = element_text(size=12)) +
  geom_hline(yintercept = 0.358, col = "red", linetype="dotted") +
  labs(x= "Patient", y= "Probability of Methylation", title = "MGMT Methylation Infinium Array Data By Hypermutation Status") +
  theme(plot.title = element_text(hjust = 0.5, face="bold"))
```
```{r}
#boxplot - BSAS data for each tumor type
ggplot(agdata, aes(x=Tumor, y=MGMT_BSAS)) +
  geom_boxplot(aes(colour=Tumor)) +
  facet_grid(. ~ HM_status, labeller = labeller(HM_status = c(HM = "Hypermutated", nonHM = "Non-Hypermutated"))) +
  theme(strip.text.x = element_text(size=12), strip.text.y = element_text(size=12)) +
  labs(x= "Patient", y= "Percentage CpG Methylation", title = "MGMT Methylation BSAS Data By Hypermutation Status") +
  theme(plot.title = element_text(hjust = 0.5, face="bold"))

```
```{r}
#Wilcox tests comparing across primaries or across recurrences
wilcox.test(agdata_primary$MGMT_Infinium~agdata_primary$HM_status)
```
```{r}
wilcox.test(agdata_recurrence$MGMT_Infinium~agdata_recurrence$HM_status)
```
```{r}
wilcox.test(agdata_primary$MGMT_BSAS~agdata_primary$HM_status)
```
```{r}
#Wilcox tests comparing between primaries and recurrences
wilcox.test(agdata$MGMT_Infinium~agdata$Tumor)
```
```{r}
wilcox.test(agdata_HM$MGMT_Infinium~agdata_HM$Tumor)
```
```{r}
wilcox.test(agdata_nonHM$MGMT_Infinium~agdata_nonHM$Tumor)
```
```{r}
#pair data
pairdata <- merge(agdata_primary, agdata_recurrence, by = c("Patient", "HM_status"))
pairdata$Tumor.x <- NULL
pairdata$Tumor.y <- NULL
colnames(pairdata)[which(names(pairdata) == "MGMT_Infinium.x")] <- "MGMT_Infinium.Primary"
colnames(pairdata)[which(names(pairdata) == "MGMT_Infinium.y")] <- "MGMT_Infinium.Recurrence"
colnames(pairdata)[which(names(pairdata) == "MGMT_BSAS.x")] <- "MGMT_BSAS.Primary"
colnames(pairdata)[which(names(pairdata) == "MGMT_BSAS.y")] <- "MGMT_BSAS.Recurrence"
pairdata_infinium <- pairdata
pairdata_infinium$MGMT_BSAS.Primary <-NULL
pairdata_infinium$MGMT_BSAS.Recurrence <-NULL
pairdata_infinium <- na.omit(pairdata_infinium)
pairdata_BSAS <- pairdata
pairdata_BSAS$MGMT_Infinium.Primary <-NULL
pairdata_BSAS$MGMT_Infinium.Recurrence <-NULL
pairdata_BSAS <- na.omit(pairdata_BSAS)

#scatterplot of paired data
ggplot(pairdata, aes(x=MGMT_Infinium.Primary, y=MGMT_Infinium.Recurrence, color=HM_status)) + 
  geom_point() + 
  geom_text(aes(label=Patient), nudge_x=0.025) +
  labs(x= "Primary (Probability of Methylation)", y = "Recurrence (Probability of Methylation)", title = "MGMT Methylation Infinium Array Data For Paired Samples") +
  theme(plot.title = element_text(hjust = 0.5, face="bold"))
```
```{r}
#bar plot of paired data
pairdata_infinium_reshape <- melt(pairdata_infinium, id.vars = c("Patient", "HM_status"))
ggplot(pairdata_infinium_reshape, aes(x=factor(Patient), y=value, fill=variable))+
  geom_bar(stat="identity", position=position_dodge())+
  facet_grid(. ~ HM_status, scales = "free", space = "free", labeller = labeller(HM_status = c(HM = "Hypermutated", nonHM = "Non-Hypermutated"))) +
  theme(strip.text.x = element_text(size=12), strip.text.y = element_text(size=12)) +
  labs(x= "Patient", y= "Probability of Methylation", title = "MGMT Methylation Infinium Array Data For Paired Samples") +
  theme(plot.title = element_text(hjust = 0.5, face="bold")) +
  scale_fill_brewer(palette="Paired") +
  theme(legend.position="bottom")
```
```{r}
#box plot of paired data
ggplot(pairdata_infinium_reshape, aes(x=variable, y=value)) +
  geom_boxplot(aes(colour=variable)) +
  facet_grid(. ~ HM_status, labeller = labeller(HM_status = c(HM = "Hypermutated", nonHM = "Non-Hypermutated"))) +
  theme(strip.text.x = element_text(size=12), strip.text.y = element_text(size=12)) +
  geom_hline(yintercept = 0.358, col = "red", linetype="dotted") +
  labs(x= "Patient", y= "Probability of Methylation", title = "MGMT Methylation Infinium Array Data For Paired Samples") +
  theme(plot.title = element_text(hjust = 0.5, face="bold"))
```
```{r}
#Wilcox test for paired data
pairdata_infinium_HM <- pairdata_infinium[which(pairdata_infinium$HM_status == 'HM'),]
pairdata_infinium_nonHM <- pairdata_infinium[which(pairdata_infinium$HM_status == 'nonHM'),]
wilcox.test(pairdata_infinium_HM$MGMT_Infinium.Primary, pairdata_infinium_HM$MGMT_Infinium.Recurrence, paired=TRUE, alternative = "two.sided")
```
```{r}
wilcox.test(pairdata_infinium_nonHM$MGMT_Infinium.Primary, pairdata_infinium_nonHM$MGMT_Infinium.Recurrence, paired=TRUE, alternative = "two.sided")

```

